---
- hosts: all 
  gather_facts: false
  connection: local 
  vars_files:
    - all_config.yml
  tasks:
  - name: "{{ inventory_hostname }}"
    vmware_host_snmp:
      hostname: '{{ inventory_hostname }}'
      username: '{{ esxi_username }}'
      password: '{{ esxi_password }}'
      validate_certs: no
      state: enabled 
    delegate_to: localhost
