---
- hosts: all 
  gather_facts: false
  connection: local 
  vars_files:
    - all_config.yml
  tasks:
  - name: "Enable vvold rule set for all ESXi Host in given Cluster"
    vmware_host_firewall_manager:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      cluster_name: "{{ cluster_name }}"
      rules:
        - name: vvold
          enabled: False 
    delegate_to: localhost
