---
- hosts: localhost 
  gather_facts: false
  connection: local 
  vars_files:
    - all_config.yml
  tasks:
  - name: "{{ inventory_hostname }}"
    vmware_host_ntp:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      cluster_name: '{{ cluster_name }}'
      ntp_servers:
        - 192.168.125.53
        - 192.168.125.54
    delegate_to: localhost
