---
- hosts: localhost 
  gather_facts: false
  connection: local 
  vars_files:
    - all_config.yml
  tasks:
  - name: Configure NTP servers for an ESXi Host
    vmware_host_ntp:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      state: present
      ntp_servers:
        - time1.google.com 
        - time2.google.com
    delegate_to: localhost
