---
- hosts: all 
  gather_facts: false
  connection: local 
  vars_files:
    - all_config.yml
  tasks:
  - name: "{{ inventory_hostname }}"
    vmware_host_ntp:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      esxi_hostname: "{{ inventory_hostname }}" 
      ntp_servers:
        - time1.google.com 
        - time1.google.com
    delegate_to: localhost
