---
- hosts: localhost 
  gather_facts: false
  connection: local 
  vars_files:
    - all_config.yml
  tasks:
  - name: Configure NTP servers for an ESXi Host
    vmware_host_ntp:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      esxi_hostname: server01.akaicloud.com
      ntp_servers:
        - 192.168.125.53 
        - 192.168.125.54
    delegate_to: localhost
